version: "3.1"
services:
  web:
    build:
      context: ../
      dockerfile: docker/api.dockerfile
    container_name: app
    restart: unless-stopped
    env_file:
      - ../envs/local.env
    environment:
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017/local-scs?authSource=admin
      APP_PORT: 3000
      DEBUG_PORT: 9222
    volumes:
      - ../:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: ./scripts/wait-for db:27017 -- npm run watch-debug
    networks:
      - app-network
    ports:
      - 80:3000
      - 9222:9222

  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - /tmp/dbdata:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
